GET http://localhost:3000/api/boxes

###

GET http://localhost:3000/api/boxes/Fa37
### 

POST http://localhost:3000/api/boxes/
Content-Type:  application/json

{
    "id": "Fa37",
    "color": "grey",
    "size": "semi-large",
    "contains": "Water"
}

###

PUT http://localhost:3000/api/boxes/
Content-Type: application/json

{
    "id": "Fa37",
    "color": "Blå",
    "size": "prob tiny",
    "contains": "Nocco"
}

###

DELETE http://localhost:3000/api/boxes/Fa37
Content-Type: application/json